name: Flyway Migration

on: 
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment Name'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev

jobs:
  container-job:
    runs-on: ubuntu-latest
  
    steps:
    - name: Starting Postgres
      run: echo STARTING POSTGRES

    - name: Running Flyway Migration
      run: echo RUNNING FLYWAY MIGRATION
      env:
        POSTGRES_USER: ${{ secrets.DB_USER }}
        POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
        POSTGRES_DB: ${{ secrets.DB_NAME }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: ${{ secrets.DB_USER }}
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
          POSTGRES_DB: ${{ secrets.DB_NAME }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
